INSERT INTO Types (Type, Kind) VALUES ('BUILDING_PORCELAIN_TOWER', 'KIND_BUILDING');

INSERT INTO Buildings (BuildingType, Name, Description, PrereqTech, Cost, AdvisorType, MaxWorldInstances, IsWonder, RequiresPlacement, Quote, AdjacentDistrict, Housing)
VALUES ('BUILDING_PORCELAIN_TOWER', 'LOC_BUILDING_PORCELAIN_TOWER_NAME', 'LOC_BUILDING_PORCELAIN_TOWER_DESCRIPTION',
  'TECH_GUNPOWDER', 920, 'ADVISOR_TECHNOLOGY', '1', 1, 1, 'LOC_BUILDING_PORCELAIN_TOWER_QUOTE', 'DISTRICT_CITY_CENTER', 3);

INSERT INTO Building_ValidTerrains (BuildingType, TerrainType)
VALUES ('BUILDING_PORCELAIN_TOWER', 'TERRAIN_GRASS'),
        ('BUILDING_PORCELAIN_TOWER', 'TERRAIN_PLAINS'),
        ('BUILDING_PORCELAIN_TOWER', 'TERRAIN_TUNDRA');

INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES  ('BUILDING_PORCELAIN_TOWER', 'YIELD_SCIENCE', 3);

INSERT INTO Building_GreatPersonPoints (BuildingType, GreatPersonClassType, PointsPerTurn)
VALUES ('BUILDING_PORCELAIN_TOWER', 'GREAT_PERSON_CLASS_SCIENTIST', '2');


-- Grants three copies of the Porcelain Luxury Resource which provides +6 Amenities.
INSERT INTO Types
(Type, Kind)
VALUES ('RESOURCE_PORCELAIN', 'KIND_RESOURCE');

INSERT INTO Resources
(ResourceType, Name, ResourceClassType, Happiness, Frequency)
VALUES ('RESOURCE_PORCELAIN', 'LOC_RESOURCE_PORCELAIN_NAME', 'RESOURCECLASS_LUXURY', 6, 0);

INSERT INTO Requirements (RequirementId, RequirementType)
VALUES ('REQ_CITY_HAS_PORCELAIN_TOWER', 'REQUIREMENT_CITY_HAS_BUILDING');

INSERT INTO RequirementArguments (RequirementId, Name, Value)
VALUES ('REQ_CITY_HAS_PORCELAIN_TOWER', 'BuildingType', 'BUILDING_PORCELAIN_TOWER');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType)
VALUES ('REQSET_CITY_HAS_PORCELAIN_TOWER', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId)
VALUES ('REQSET_CITY_HAS_PORCELAIN_TOWER', 'REQ_CITY_HAS_PORCELAIN_TOWER');


INSERT INTO Modifiers (ModifierId, ModifierType) VALUES ('PORCELAIN_TOWER_CITIES_FREE_PORCELAIN', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER','REQSET_CITY_HAS_PORCELAIN_TOWER');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent) VALUES ('PORCELAIN_TOWER_CITY_FREE_PORCELAIN', 'MODIFIER_SINGLE_CITY_GRANT_RESOURCE_IN_CITY', 1, 1);

INSERT INTO  ModifierArguments (ModifierId, Name, Value) VALUES ('PORCELAIN_TOWER_CITIES_FREE_PORCELAIN', 'ModifierId', 'PORCELAIN_TOWER_CITY_FREE_PORCELAIN');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('PORCELAIN_TOWER_CITY_FREE_PORCELAIN', 'ResourceType', 'RESOURCE_PORCELAIN');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('PORCELAIN_TOWER_CITY_FREE_PORCELAIN', 'Amount', 3);

INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES ('BUILDING_PORCELAIN_TOWER', 'PORCELAIN_TOWER_CITIES_FREE_PORCELAIN');